### PR TITLE
Fix need userinfo endpoint

### LINKED ISSUE #10: Handle unavailable UserInfo endpoint
Hi,
currently [Dex](https://github.com/coreos/dex/) doesn't provide a `UserInfo` URL. But it is also not mandatory according to [OpenID specifications](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).
Consequently, the package crashes [here](https://github.com/switch-ch/meteor-accounts-oidc/blob/master/packages/switch:oidc/oidc_server.js#L101), when trying to get the `UserInfo`.

Is there a way to configure the package, such that it doesn't query the `UserInfo`?
Cheers!

### PR DESCRIPTION
**Pull request by Gimly**
Some identity providers don't support the user_endpoint, since it's marked only as "recommended" in the OpenID Connect specifications. This pull request removes the need to have the user_endpoint setup. If it's not setup, it will look for the information about the user in the received token. If the user_endpoint is setup in the configuration, it will call the endpoint and do the same thing as before the pull requests.

I've also added support for if the server returns an id_token and not an access_token.

Finally, I again changed the folder names because I saw that, on Windows, Meteor replaces the ":" in the folder names by "_". This way we will be coherent with how Meteor manages the packages.

Closes #10

### CODE REVIEW

**Review by marcosterland — CHANGES_REQUESTED** [review]
Good Work. The required `jwt-simple` package ([here](https://github.com/switch-ch/meteor-accounts-oidc/pull/13/commits/7347c24ac58420711ca825c656f03956f6d9d77f#diff-fdc843a1c13dc2f89a230fe2bafdd1efR86)) should show up in the package's `package.js`.

**Comment by Gimly** [comment]
I'm not using it anymore, I've removed those lines in the next commit. You can check that it's not present in the final commit by looking at the files changed.

**Comment by Gimly** [comment]
If you don't want the intermediate commits which are not very useful, you can do a squash merge.

**Comment by marcosterland** [comment]
@Gimly Oh yeah, nevermind!

**Comment by valerytschopp** [comment]
Thanks a lot for this fix, good work.

**Comment by Gimly** [comment]
You're welcome. I needed it for our project, so it's best if it helps everyone .

**Pull request merged**
